---
title: "HRT101.S1"
subtitle: "Introduction to Health Research: Study Designs and Sampling Methods"
author: "Md. Jubayer Hossain <br/> Founder, CHIRAL Bangladesh"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ["default", "css/chiral.css", "css/chiral-fonts.css"]
    lib_dir: libs
    nature:
      ratio: 16:9
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html") 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "65%", cache = FALSE)

library(ymlthis)
library(tidyverse)
library(xaringanExtra)
library(palmerpenguins)
xaringanExtra::use_panelset()
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(
  share_buttons = c("twitter", "linkedin", "pocket")
)
```

## Agenda 
- Basic Epidemiology
- Study Designs
- Sampling Methods



---
class: inverse center, middle
# Basic Epidemiology

---
## Steps in the Paradigm of Public Health
- Define the problem
- Measure its magnitude
- Understand the key determinants
- Develop intervention/prevention strategies
- Set policy/priorities
- Implement and evaluate

---
## Quantitative Methods
- Epidemiology and biostatistics are the basic sciences of
public health
- Public health investigations use quantitative methods,
which combine the two disciplines of epidemiology and
biostatistics
- Epidemiology is about the understanding of disease
development and the methods used to uncover the etiology,
progression, and treatment of the disease
- Information (data) is collected to investigate a question
- The methods and tools of biostatistics are used to analyze the
data to aid decision making



---
## Epidemiology
**Epidemiology** is the study of the distribution and
determinants of health, disease, or injury in human
populations and the application of this study to the control of
health problems



---
## Epidemiology as a Science and a Method
- Epi = upon, among
- Demos = people
- Ology = science, study of
- Epidemiology = the science or the study of epidemic
− It is the scientific method of disease investigation
  − Typically, it involves the disciplines of biostatistics and
  medicine


---
## John Snow (1813–1858)
- An English physician and modern-day father of epidemiology
- He used scientific methods to identify the cause of the
epidemic of cholera in London in 1854
- He believed that it was the water pump on Broad Street that
was responsible for the disease
  − The removal of the pump handle ended the outbreak


---
## A Definition of Epidemiology
The study of distribution and determinants of health,
disease, or injury in human populations and the application
of this study to the control of health problems


---
## Types of Epidemiology
.pull-left[
Distribution
− Frequency of health events
− By person, time and place

Determinants
− Search for causes or risk factors
− Response to a study hypothesis
− Use various epidemiologic methods

]

.pull-right[
- Descriptive
epidemiology
- Analytic
epidemiology


]


---
## Objectives of Epidemiology
- Investigate the etiology of disease and modes of transmission
- Determine the extent of disease problems in the community
- Study the natural history and prognosis of disease
- Evaluate both existing and new preventive and therapeutic
measures and modes of health care delivery
- Provide a foundation for developing public policy and
regulatory decisions


---
## Uses of Epidemiology
- In historical study of health and diseases in the population
and in projecting into the future
- For community diagnosis of the presence, nature and
distribution of health and diseases among the population
- To study the working of health services
- To estimate the individual’s chances and risks of disease
- To help complete the clinical picture of diseases
- In identifying syndromes from the distribution of clinical
phenomena among sections of the population
- In the search for causes of health and disease


---
## Definition of Endemic, Epidemic, and Pandemic
- Endemic
  − The habitual presence of a disease within a
  given geographic area
  − May also refer to the usual prevalence of a
  given disease within such an area (APHA)

- Epidemic
  − The occurrence in a community or region of a
  group of illnesses of similar nature, clearly in
  excess of normal expectancy (APHA)
  − Outbreak

- Pandemic
  − A worldwide epidemic

  




---
## Population at Risk
- Proportion of a population that is succesptible to a disease
- Can be defined on the basis of demographic or environmental factors


---
## Population at Risk: Examples 
- Proportion of a population that is succesptible to a disease
- Can be defined on the basis of demographic or environmental factors

---
## Prevalence - (P)
- Number of existing cases (old and new) in a defined population at a specified point of time. 


---
## Point Prevalence 





---
## Period Prevalence - (PP)



---
## Factors Influencing Prevalence 



---
## Cause of Increase and Decrease of Prevalence 



---
## Use of Prevalence Data 


---
## Incidence(I)




---
## Cumulative Indcidence(CI)



---
## Risk 




---
## Indence Density(ID)



---
## Use of Incidence Data 




---
## The dynamic Incidence and Prevalence 



---
## The Relation between Prevalence and Incidence 



---
## Patterns of Incidence and Prevalence 



---
## Case Fatality



---
class: inverse, center, middle 
# Study Designs 



---
## Epidemiological Studies 



---
## Types of Studies 




---
## Descriptive Study Designs 



---
## Types of Descriptive Studies 



---
## Case Reports 




---
## Case Series 




---
## Ecological Studies 



---
## Cross Sectional Study 





---
## Uses of Cross-sectional Studies 





---
## Example of Research Questions to be Adressed through Surveys



---
## Advantages and Limitations of Cross-sectional Studies 




---
## Cross-sectional Surveys: Major limitations 




---
class: inverse, center, middle 
# Analytical Studies 



---
## Analytical Studies 



---
## Cohort Study 





---
## Designs of Cohort Studies 



---
## Type of Cohort Studies 



---
## Elements of Cohort Studies 



---
## Selection of Study Population 




---
## Gathering Baseline Informations




---
## Choice of Comparison Group




---
## Follow-up





---
## Case-control Studies 





























































---
class: center, middle

# Thanks!

Find me: <br/>
Email: [contact.jubayerhossain@gmail.com](#)<br/>
Website: https://jhossain.com/<br/> 
Github: https://github.com/hossainlab<br/>