---
title: "HRT101"
subtitle: "Introduction to Health Research: Literature Review"
author: "Md. Jubayer Hossain <br/> Founder, CHIRAL Bangladesh"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ["default", "css/chiral.css", "css/chiral-fonts.css"]
    lib_dir: libs
    nature:
      ratio: 16:9
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html") 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "65%", cache = FALSE)

library(ymlthis)
library(tidyverse)
library(xaringanExtra)
library(palmerpenguins)
xaringanExtra::use_panelset()
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(
  share_buttons = c("twitter", "linkedin", "pocket")
)
```

## Agenda 
- Literature Review

--

- Smart Google Searching


--


- Literature Databases


--

- Developing a Health Research Topic


--

- Using Google Scholar

--

- Using PubMed

--

- Other Biomedical Databases


---
class: inverse center middle

#  Literature Review

---
## Why Lerform a Literature Review?
- Saves yourself from work!

--

- Know the subject matter better

--

- Suggest new research topics, questions and methods

---
## Literature Review: Not Just A Summary!
- **Information seeking:** Scan the literature efficiently using manual or computerized methods to identify a set of potentially useful articles and books

--

- **Critical appraisal:** The ability to apply principles of analysis to identify those studies which are unbiased and valid.

---
## Literature Review: Organized Search
1. Develop question for further research

--

2. Synthesize results summary of what is and isn’t known

--

3. Organize information relate it to the research question

--

4. Identify lacunae As appears in the literature

--

5. **Information retrieval:** identifying, within a large document collection, a subset of documents whose content is most relevant to the user’s need

---
## Literature Review: Selecting Studies
- Step 1: Tabulate info from each study and Compare

--

- Step 2: Select those of good quality

--

- Step 3: Read and critique studies

--

- Step 4: Compare methods, results, findings, etc


---
## Literature Review: Writing a Literature Review -  Introduction
1. Purpose of review

--

2. Organization of review

--

3. Basis for ordering

--

4. Most important to least

--

5. Earliest to most recent

---
## Literature Review: Writing a Literature Review -  Empirical Literature
1. Includes quality studies relevant to the topic

--

2. Explain each study using paraphrasing rather than direct quotes

--

3. Scholarly, but brief, critique of study’s strengths and weaknesses


---
## Literature Review: Writing a Literature Review -  Summary
Concise presentation of the research knowledge about a selected
topic—what is known and not known. 

---
## Literature Review: Ethical Issues
- Content from studies - presented honestly - not distorted

--

- Weaknesses of a study - addressed, not necessary to be highly critical

--

- Sources should be accurately documented





---
class: inverse center middle

# Smart Google Searching 


---
## Smart Google Searching: Search Tips 
- Conduct advanced searches into two ways 
  - By integrating Advanced Search Operators(ASO) into the search
  - By using the search engine's dedicated advance search page
.footnote[
[Source: Google; Accessed January 11, 2022, at https://developers.google.com/search/docs/advanced/]()
]


---
## Smart Google Searching: Symbols as Search Operators
| Operators | Description|  Example & Syntax	| 
|:--------|:---------|:-------------|
|Quotation marks (" ") | Results include the search terms when they appear as a phrase|  "cell phones"|
|Hyphen ( - ) | You can use the hyphen to indicate that words are strongly connected| smoking - cancer| 
|Hyphen ( - ) | You can use the hyphen to exclude words from a search query|cancer -adults|


---
## Smart Google Searching: Boolean Operators
| Operators | Description|  Example & Syntax	| 
|:--------|:---------|:-------------|
|OR| Broaden your search using the OR operator |"cell phones" OR "mobile phones"|
|AND| Narrow down your search using AND operator | "mental health" AND "cell phones"| 


---
## Smart Google Searching: Advanced Search Operators 
- Add operators to searches to help narrow down results 
- Use operators not readily available from the Advanced Search Page


---
## Smart Google Searching: Advanced Search Operators - Site 
- site: 
  - Limits search results to a website or domain 
- Examples 
  - site:.gov - limits results to government websites 
  - site:.edu - limits results to educational websites 
  - site:.org - limits results to organizational websites 
  - site:cdc.gov - limits results to the CDC within government websites
  - site:.bd - limits results to websites in the country Bangladesh

.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]


---
## Smart Google Searching: Advanced Search Operators - Filetype 
- filetype:
  - Limits search results to .pdf, .ppt, .xls, .doc, etc
- Examples
  - filetype:ppt - Finds only powerpoint slides
  - filetype:pdf - Finds only pdf files
  - filetype:doc - Finds only word documents 
  - filetype:xls - Finds only excel files
  - filetype:ppt AND "lung cancer"

.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]

---
## Smart Google Searching: Advanced Search Operators - Combinations  
- Example of several operators in one search
  - filtetype:pdf site:bd "coronavirus"
    - Finds only PDF articles about corona virus hon Bangladeshi websites

.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]

---
## Smart Google Searching: Filters and Limits   
- Limit to:
  - Custom date range 
  - Date attached  to record 
  - Sort results 
  
- Example:
  - filtetype:pdf site:bd "coronavirus" 
  - Customize results by date 

.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]


---
class: inverse center middle

# Developing a Health Research Topic


---
## Start Somewhere


- Your interest or background 
  - course topic 

--

- Professional organization or government agency hot topics 
  - American Nursing Association 
  - National Institute of Health 
  - World Health Organization


--


- What's happen related to health in your geographical area of study? 
  - News, local initiatives, local organizations, etc. 


---
## Smart Google Searching: Brainstorming Trick

- Government Sites -  **site:.gov (topic AND geography)**

--


-  Organizational Sites - **site:.org (topic AND geography)**


--


- Educational Sites - **site:.edu (topic AND geography)**
.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]


---
## Smart Google Searching : A Practical Example

- What is the broad topic?
  - Maternal death

--

- Who does it impact? or who could it impact?
  - Expecting mothers, children/physicians/healthcare professionals


--

- When does this matter? At what time are you interested in this topic?
  - Last 5- 10 years


--

- Where do you want to focus?
  - Bangladesh
  
--

- Searching Strategies - **site:.gov (topic AND geography)**
  - site:.gov (maternal death AND Bangladesh)
 

---
## Using Search Results
- Write down search results 
- Framing possible research question

**Research Question:**
In Bangladesh, what disparities among expecting women are associated with maternal death(pregnancy related mortality)? 



---
class: inverse center middle

# Literature Databases



---
## What are Literature Databases? 


- Literature Databases are used to identify articles from peer-reviewed journals and other types of periodicals. 


--

- These databases are created by companies and other entities and are subscribed to by or licensed to academic and other institutions.


--

- In general, databases provide general information about individual articles and other content, such as the article title, author name, date of publication, descriptor words, and article summary (abstract).


--


- Major database producers provide a lot more details, and can allow the use of quite sophisticated searching strategies so that you can find the perfect paper.
.footnote[
[Source: Illinois Library; Accessed January 11, 2022, at https://guides.library.illinois.edu/](#)
]


---
class: inverse center middle

# Literature Searching



---
## Literature Searching: An Introduction
- Frame your research questions
- Keyword Searching: Three steps 
  - Identify keywords - main concepts 
  - Identify synonyms - to find them try looking them into Google and dictionaries or journal articles 
  - Combining keywords using search operators 
  
---
## Literature Searching: A Practical Example
**Research Question:**
How are mobile apps currently being used to help individuals with hypertension eat a healthier diet? 

- `Concept 1:` Mobile apps 
	- **Keywords:** mobile applications, mobile apps, mobile technologies, mobile healthcare, mhealth
	- **Combining Keywords:**  mobile applications OR mobile apps OR mobile technologies OR mobile healthcare OR mhealth
- `Concept 2:` Diet 
	- **Keywords:** diet, nutrition  
	- **Combining Keywords**: diet OR nutrition  
- `Concept 3:` Blood pressure  
	- **Keywords:** hypertension, high blood pressure
  - **Combining Keywords:** hypertension OR high blood pressure




---
class: inverse center middle

# Using Google Scholar 


---
## Google Scholar: Overview 
- Google Scholar provides a simple way to broadly search for scholarly literature. 

--

- From one place, you can search across many disciplines and sources: articles, thesis, books, abstracts and court opinions, from academic publishers, professional societies, online repositories, universities and other web sites.

--

-  Google Scholar helps you find relevant work across the world of scholarly research.
.footnote[
[Source: Google Scholar; Accessed January 11, 2022, at https://scholar.google.com/intl/en/scholar/about.html]()
]


---
## Google Scholar: Why Use It?
- Relevancy(relevant hits at the top of the list; tend to be older)

--

- Web-based materials not in other databases

--

- Searches a broad cross-section of subjects and disciplines

--

- "Cited by" links to works that cite a particular book or article 

--

- Links to University Library 

---
## Google Scholar: Advantages 

- Google Scholar is familiar and relatively simple to use, much like Google.

--

- Google Scholar allows users to search for find a wide variety of materials including articles, books, "grey literature" like conference proceedings on a vast number of topics.

--

- Google Scholar allows for you to see articles related to the one that might interest you, how many times an article has been cited and by whom, and provides citations for articles in a number of styles.

--

- Google Scholar can display links to articles and books held through ECU Libraries. For more information, see Using Google Scholar from Home tab.

--

- Google Scholar allows you to save both citations and articles to read later.

.footnote[
[Source:East Carolina University Libraries; Accessed January 11, 2022, at https://libguides.ecu.edu/]()
]


---
## Google Scholar: Disadvantages

- Google Scholar's coverage is wide-ranging but not comprehensive. It can be a research source, but should not be the only source you use.

--

- Google Scholar does not provide the criteria for what makes its results "scholarly". Results are often vary in quality and it is up to the researcher to determine which of the results are suitable for their purposes.

--

- Google Scholar does not allow users to limit results to either peer reviewed or full text materials or by discipline.

--

- Google Scholar does not provide notice of when its materials are updated.

--

- Google Scholar's citation tracker can be difficult to use and inaccurate.

.footnote[
[Source:East Carolina University Libraries; Accessed January 11, 2022, at https://libguides.ecu.edu/]()
]


---
## Google Scholar: Content - Use with Caution!
- Frequency of updates unknown 

--

- Gaps in coverage 

--

- May omit year, issu numbers, or journal titles

--

- Bias towards older literature, much of which is not full text

.footnote[
[Source: Mayr, P., & Walter, A. K. (2008). Studying journal coverage in Google Scholar. Journal of Library Administration, 47(1-2), 81-99]()
]

---
## Default Google Scholar Search Settings
- Not case sensitive - capital letters of search terms are ignored

--

- `AND` - search terms are automatically combined using AND

--

- keyword - searches the full text of scholarly material, including citation and abstract


---
## Options to Refine Your Search - 1
| Options | Description|  Example & Syntax	| 
|:--------|:---------|:-------------|
|Synonyms | Google automatically searches for matching and similar meaning words| mobile phones, cell phones, smartphones, mobile technology|
|Phrase searching | Use quotation marks around phrases | “hearing loss”, "cell phones", "mobile technology"| 
|OR | Results include either search term. OR must be in capital letters | smartphones OR "cell phones"|


---
## Options to Refine Your Search - 2
| Options | Description|  Example & Syntax	| 
|:--------|:---------|:-------------|
|Exclude |Use `–` immediately before a search term you want to exclude| cancer – adult|
|Include | Use `+` immediately before automatically excluded search terms that you want included| cancer +children| 
|Intitle | Finds results with your search term in the document title |intitle:cancer|

.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]


---
## Options to Refine Your Search - 3
| Options | Description|  Example & Syntax	| 
|:--------|:---------|:-------------|
|Author |Finds results with your search term as the document author| author:Jones|
|Date range| To change from Any time, select an option from left side of the results screen|Since 2021, 2015 to 2020| 
|Document type| Choose Articles or Case law or My library, or deselect include patents|Books, Journals, Review Articles, etc|
.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]


---
## Options to Refine Your Search - 4
| Options | Description|  Example & Syntax	| 
|:--------|:---------|:-------------|
|intext |Results include a specific search term in the body of the article|  intext:cancer|
|source| Results include articles published in a particular journal|source:"journal title"| 
|ininventor| Results include patent related documents including the name of a patent inventor|ininventor:"first name last name"|
|assignee| Results include patent related documents including the entity that is granted the ownership of the patent|assignee:"entity name"|

.footnote[
[*] [ Tip! Do not add a space after the colon.]()
]


---
## Google Scholar: Boolean Operators -1 
| Boolean & Proximity Operators | Description|  Example & Syntax	| Tips | 
|:--------|:---------|:-------------|:-------------|
|AND | Finds both terms included in a search query, so it narrows down search results | boys `AND` anxiety | Good practice when you want to combine more than one search terms. It needs to be in capital letters| 
|OR| Finds one or either terms included in a search query, so it expands search results| cancer (smartphones `OR` mobile phones) |   Good practice when there is more than one commonly used set of keywords that describe a topic. It needs to be in capital letters|

.footnote[
[Adapted from John S. Bailey Library; Accessed January 11, 2022, at https://library.acg.edu/how-to-guides/google-scholar/advanced-searching]()
]

---
## Google Scholar: Boolean Operators -2
| Boolean & Proximity Operators| Description|  Example & Syntax	| Tips | 
|:--------|:---------|:-------------|:-------------|
|NOT| Finds the first term included in a query but not the second, so it narrows down search results| cancer `-` adult| Good practice when not useful words pop up in your results. Do not spell out the word NOT use the minus symbol or a hyphen (-) instead. Do not add a space after the hyphen. The search term you wish to exclude should appear immediately after it|
|AROUND | Allows to search by proximity of words, so it narrows down search results | library anxiety `AROUND (5)` graduate |   It should be written in capital letters. You can add spaces between the first search term(s), `AROUND`, the parenthesis with the number that indicates how close the next search term should appear in the results and the second search term(s)|
.footnote[
[Adapted from John S. Bailey Library; Accessed January 11, 2022, at https://library.acg.edu/how-to-guides/google-scholar/advanced-searching]()
]


---
## Google Scholar: Advanced  Search
- The advanced search allows you to search more precisely. 

- Use the articles dated between option to limit to specific years.

- Try the authored by search box to see resources by a specific author

- Explore the other search options to see what's most effective for your search, such as searching in specific journals, searching for exact phrases, and using different keyword strategies.

---
## Google Scholar: Interpreting the Results Screen
- Cited by - Which leads you to other articles available to Google's robots.
- Related articles - Links to other results, found by Google Scholar, that have cited this document. 
- All versions - Link to other versions of this document found by Google Scholar

---
class: center middle

# Google Scholar: Building a Search

---
class: center middle

# Using Google Docs: <br/> A Systematic Approach for Google Scholar Search


---
class: center middle

# Google Scholar: <br/> Creating Literature Matrix using Library




---
class: inverse center middle

# Using PubMed


---
## PubMed Overview 
- Produced by the National Library of Medicines(NLM)
- One of the largest biomedical literature databases
- Provide free access to MEDLINE 
- Covers medicines, public health, nursing, dentistry and much more

.footnote[
[Source: PubMed; Accessed January 11, 2022, at https://pubmed.ncbi.nlm.nih.gov/]()
]


---
## Difference Between MEDLINE and PubMed 
- MEDLINE is NLM's database of journal citations and abstracts for biomedical literature.
- MEDLINE citations have been indexed and reviewed for accuracy
- Medical Subject Headings(MeSH) are  specialized subject headings (controlled vocabulary) used to index citations in MEDLINE



---
class: inverse center middle

# PubMed: Basics of Searching

---
## PubMed Search: Searching Information
- Looking for high-quality articles to answer specific questions 
- Scoping the literature to see what’s been published 
- Conducting an in-depth literature review 


---
## PubMed Search: Common Searching Techniques 
- Boolean operators AND & OR 
- Nesting to group similar terms 
- Truncation for words with multiple endings 
- Quotes for phrases 


---
## PubMed Search: Search Scenario
> Possible risk of mobile phones causing cancer in children 


---
## PubMed Search: Combined Terms with AND 
- Cancer AND children AND mobile phones 
  - Find articles that include all three terms. 


---
## PubMed Search: Combined Terms with OR 
- Cancer AND children AND mobile phones 
  - Find articles that include all three terms. 

- Mobile phones OR smartphones OR cell phones
  - Find articles on any of these topics 
  - Use OR with synonyms or similar terms to expand the number of results. 


---
## PubMed Search: Combined Terms with NOT 
- Cancer NOT leukemia 
  - It looks for articles about cancer but removes articles that talk about leukemia. 

---
## PubMed Search: Caution about NOT 
- Children NOT adults 
  - Removes citations that could be relevant 
  - Miss article that addresses adults and children 


---
## PubMed Search: Use of Boolean Operators 
- Use all caps for ANDs and ORs.

---
## PubMed Search: Nesting
- Children AND cancer AND mobile phones OR smartphones OR cell phones
  - PubMed uses an algorithm to search 

- Children AND cancer AND mobile phones OR smartphones OR cell phones
    - PubMed reads from left to right 

---
## PubMed Search: Nesting Parentheses 
- Cancer AND children ANd (mobile phones OR smartphones OR cell phones)
- Phrasing 
  - PubMed automatically adds an AND between words 
  - Can cause problems with phrases like cell towers

- Put double quotation marks around phrases
  - “Cell phones”, “mobile phones”
  - You don’t need quotes around single words such as smartphones

- Truncation Symbol
  - The PubMed truncation symbol is the asterisk(*) 
  - Truncation uses word stems and matches various words endings
  


---
class: inverse center middle

# PubMed: Filters and Field Tags

---
## PubMed Filters: What are filters?
- Results by year 
- Text Availability 
- Article attribute 
- Article type 
- Publication date 
- Additional filters 

---
## PubMed Field Tags: What are filters used for?
- Used  to quickly access a few articles
- Standard used for systematic review 

---
## PubMed Field Tags: What are field tags?
- Special tag typed at end of search term
- Use brackets 

---
## PubMed Field Tags: Most Common Field Tags

- [au] - looks for article written by an author 
- [tiab] - title or abstract 
- [tw] - search for keyword in title, abstract, author supplied keywords, etc. 
- [ti] - search for keyword in title 
- Examples: 
  - cancer[tiab] AND children[tiab] AND mobile phones[tiab]
  - cancer[tw] AND children[tw] AND mobile phones[tw]
  - cancer[ti] AND children[ti] AND mobile phones[ti]



---
class: inverse center middle

# PubMed: Building a Search


---
## Systematic Approach for Finding Relevant Articles 
- Use a combination of Medical Subject Heading(MeSH) and Keywords
- Incorporate Boolean Operators, truncation, and field tags
- Run your search in PubMed


---
## Research Question and Key Concepts 
> How are mobile apps currently being used to help individuals with high blood pressure eat a healthier diet?  

- Key Concepts: mobile apps AND diet AND blood pressure 


---
## Searching Strategies 
- **Research Question:**How are mobile apps currently being used to help individuals with high blood pressure eat a healthier diet?  

- **Concept 1:** Mobile apps 
  - **Keywords:** mobile application(s), mobile technology(ies), mHealth

- **Concept 2:** Diet 
  - **Keywords:** diet, nutrition
  
- **Concept 3:** Blood pressure 
  - **Keywords:** hypertention, high blood pressure


---
## Identify relevant MeSH for research question
> **MeSH** refers to the specialized subject headings, or controlled vocabulary, used in **Medline**. All Medline articles are indexed with his vocabulary

- Examples: 
  - "Mobile Applications"[Mesh]
  - Diet Therapy"[Mesh]
  - "Hypertension"[Mesh]


---
class: center middle

# Using Google Docs: <br/> A Systematic Approach for PubMed Search




---
class: inverse center middle

# PubMed: Using Advanced Search




---
class: inverse center middle

# Medline: Advance Searching 

---
## Medline: Overview 
- MEDLINE is a bibliographic database of life sciences and biomedical information.
- It includes bibliographic information for articles from academic journals covering medicine, nursing, pharmacy, dentistry, veterinary medicine, and health care.
.footnote[
Source:  Wikipedia; Accessed January 11, 2022, at https://en.wikipedia.org/wiki/MEDLINE
]


---
class: inverse center middle

# ProQuest: Advance Searching 


---
# ProQuest: Overview 
ProQuest LLC was an Ann Arbor, Michigan-based global information-content and technology company, founded in 1938 as University Microfilms by Eugene B. Power.
.footnote[
Source:  Wikipedia; Accessed January 11, 2022, at https://en.wikipedia.org/wiki/ProQuest
]


---
class: inverse center middle

# Scopus: Advance Searching 

---
# Scopus: Overview 
- Scopus is Elsevier's abstract and citation database launched in 2004.
- Scopus covers nearly 36,377 titles from approximately 11,678 publishers, of which 34,346 are peer-reviewed journals in top-level subject fields: life sciences, social sciences, physical sciences and health sciences. 
.footnote[
Source:  Wikipedia; Accessed January 11, 2022, at https://en.wikipedia.org/wiki/Scopus
]



---
class: inverse center middle

# CINAHL: Advance Searching 


---
# CINAHL: Overview 
- CINAHL is an index of English-language and selected other-language journal articles about nursing, allied health, biomedicine and healthcare.
- Ella Crandall, Mildred Grandbois, and Mollie Sitner began a card index of articles from nursing journals in the 1940s.
.footnote[
Source:  Wikipedia; Accessed January 11, 2022, at https://en.wikipedia.org/wiki/CINAHL
]

---
class: inverse center middle

# PsycINFO: Advance Searching 


---
# PsycINFO: Overview 
- PsycINFO is a database of abstracts of literature in the field of psychology.
- It is produced by the American Psychological Association and distributed on the association's APA PsycNET and through third-party vendors. 
- It is the electronic version of the now-ceased Psychological Abstracts
.footnote[
Source:  Wikipedia; Accessed January 11, 2022, at https://en.wikipedia.org/wiki/PsycINFO
]


---
class: center, middle

# Thanks!

Find me: <br/>
Email: [contact.jubayerhossain@gmail.com](#)<br/>
Website: https://jhossain.com/<br/> 
Github: https://github.com/hossainlab<br/>