---
title: "HRT101.S1"
subtitle: "Introduction to Health Research:  Scientific Paper Reading and  Research Data Management"
author: "Md. Jubayer Hossain <br/> Founder, CHIRAL Bangladesh"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ["default", "css/chiral.css", "css/chiral-fonts.css"]
    lib_dir: libs
    nature:
      ratio: 16:9
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html") 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "65%", cache = FALSE)

library(ymlthis)
library(tidyverse)
library(xaringanExtra)
library(palmerpenguins)
xaringanExtra::use_panelset()
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(
  share_buttons = c("twitter", "linkedin", "pocket")
)
```

## Agenda 
- Research Data Management
- Scientific Paper Reading
- Literature Review Matrix 

---
class: inverse center middle

#  Research Data Management(RDM)



---
## What is Research Data Management(RDM)?
- Research data management (RDM) refers to the organisation, storage and preservation of data created during a research project

--

- It covers initial planning, day-to-day processes and long-term archiving and sharing.

.footnote[
[Source: The University of Scheffield; Accessed January 14, 2022, at https://www.sheffield.ac.uk/library/]()
]


---
## Why Research Data Management(RDM)
To ensure that research data are: 

--

- Secure 

--

- Sustainable 

--

- Reusable  



---
## What is Research Data?
> **Research Data**<br>
> Any information collected or generated for the purpose of analysis, in order to generate or validate scientific claims. 

---
## Types of Research Data?
Research data can be classified in different ways: 
--

- Content - Numerical, textual, audiovisual, multimedia, etc. 

--

- Format - Spreadsheets, databases, images, maps, audios, files, and unstructured text. 

--

- Methods - Experimental, observational, simulation, derived. 

--

- Nature - Digital(born-digital or digitized) or non-digital(paper surveys)

--

- Source - Primary, secondary 

--

- Processing - Raw, processed 



---
## Steps in Research Data Management(RDM)
- Planning 

--

- Collecting 

--

- Organizing 

--

- Documenting 

--

- Storing 

--

- Backing-up 

--

- Preserving 

--

- Sharing 


---
## Research Data Lifecycle 

- Before Research - Planning 

--

- During Research - Collecting, Organizing, Documenting, Storing, Backing-up 

--

- After Research - Sharing, Preserving 



---
## Benefits of Managing and Sharing Data
- Minimizing your risk of losing valueable data 

--

- Increasing your research efficiency 

--

- Facilitating collaborative research 

--

- Supporting research quality and integrity 

--

- Enhancing the visibility and impact of your research 

--

- Complying with(external) data requirements 

--

- Accelerating scientific discovery

--

- Increasing return on investment 


---
class: inverse center, middle

# Anatomy of a Scientific Paper


---
## Anatomy of a Scientific Paper
- Abstract
- Introduction / Background
- Methods
- Results
- Discussion
- Conclusion

---
## Anatomy of a Scientific Paper: Abstract
- Purpose - Mini version of the paper
- Length - 200-250 words
- Tense - Simple Past Tense
- Elements: 
  - Objectives
  - Methods
  - Results
  - Conclusions

---
## Anatomy of a Scientific Paper: Introduction
- Purpose - Provides rational of the study
- Length - 500-1000 words
- Tense - Simple Past Tense
- Elements: 
  - Nature and scope of the problem
  - Review of relevant literature
  - Hypothesis 
  - Approach(Justification for this approach)
  - Principal results 
  - Objectives/Main conclusions 


---
## Anatomy of a Scientific Paper: Methods
- Purpose - Describe what was done? experiment, model or field study
- Length - 500-1000 words 
- Tense - Simple Past Tense - refers to work done 
- Elements: 
  - Description of instruments 
  - Description of procedure in logical order 
  - Significant details so that procedure can be reproduced 
  - Sampling 
  - Data collection
  - Measurement

---
## Anatomy of a Scientific Paper: Results
- Purpose - Presents the data, the facts what researchers found.
- Keywords - calculated, investigated, observed, discovered 
- Length - 500-15000 words 
- Tense - Simple Past Tense - refers to what was found, observed or investigated 
- Elements: 
  - Results 
  - Observations during experiment or fieldwork 
  - Observations about the results(e.g, compare/contrast between experiments)
  - Sampling 
  - Results of calculation using data, such as rates, ratio or errors

---
## Anatomy of a Scientific Paper: Discussion 
- Purpose - Shows the relationship among the facts, puts results in context of previous research
- Keywords - calculated, investigated, observed, discovered 
- Length - 1000-15000 words 
- Tense - Simple Present Tense - emphasis on established knowledge and present knowledge
- Elements: 
  - Trends, relationships, generalizations shown by the results
  - Any exceptions, outlying data(and why)
  - How researcher's result agree or disagree with previous studies, and why?
  
---
## Anatomy of a Scientific Paper: Conclusion 
- Purpose -  Summarize principal findings
- Keywords - calculated, investigated, observed, discovered 
- Length - 1000-15000 words 
- Tense - Simple Present Tense - emphasis on what should now be accepted as established knowledge.
- Elements: 
  - Trends, relationships, generalizations shown by the results
  - Any exceptions, outlying data(and why)
  - How researcher's result agree or disagree with previous studies, and why?



---
## Reading Scientific Paper  
- Read the abstract first
- Full-article review
- Minimum 20
- Include any available systematic review on the topic



---
class: inverse center, middle

# How to Read a Scientific Paper Quickly? 

---
## Three Pass Approach 
Each pass accomplishes specific goals and builds upon the previous pass:
-  The first pass gives you a general idea about the paper. 
- The second pass lets you grasp the paper’s content, but not its details
- The third pass helps you understand the paper in depth.

.footnote[
[*] [Adapted from Keshav, Srinivasan. "How to read a paper." ACM SIGCOMM Computer Communication Review 37.3 (2007): 83-84.]()
]

---
## Three Pass Approach: The First Pass
- The first pass is a quick scan to get a bird’s-eye view of
the paper.
- You can also decide whether you need to do any
more passes.
- This pass should take about five to ten minutes
and consists of the following steps:
  -  Carefully read the title, abstract, and introduction
  - Read the section and sub-section headings, but ignore
  everything else
  - Read the conclusions

.footnote[
[*] [Adapted from Keshav, Srinivasan. "How to read a paper." ACM SIGCOMM Computer Communication Review 37.3 (2007): 83-84.]()
]


---
## Three Pass Approach: The First Pass
- The first pass is a quick scan to get a bird’s-eye view of
the paper.
- You can also decide whether you need to do any
more passes.
- This pass should take about five to ten minutes
and consists of the following steps:
  -  Carefully read the title, abstract, and introduction
  - Read the section and sub-section headings, but ignore
  everything else
  - Read the conclusions
  - Glance over the references, mentally ticking off the
ones you’ve already read


.footnote[
[*] [Adapted from Keshav, Srinivasan. "How to read a paper." ACM SIGCOMM Computer Communication Review 37.3 (2007): 83-84.]()
]



---
## Three Pass Approach: At The End of First Pass
You should be able to answer the five Cs:
1. Category: What type of paper is this? A measurement paper? An analysis of an existing system? A
description of a research prototype?
2. Context: Which other papers is it related to? Which
theoretical bases were used to analyze the problem?
3. Correctness: Do the assumptions appear to be valid?
4. Contributions: What are the paper’s main contributions?
5. Clarity: Is the paper well written?

.footnote[
[*] [Adapted from Keshav, Srinivasan. "How to read a paper." ACM SIGCOMM Computer Communication Review 37.3 (2007): 83-84.]()
]


---
## Three Pass Approach: The Second Pass
- In the second pass, read the paper with greater care, but
ignore details such as proofs. 
-  It helps to jot down the key points, or to make comments in the margins, as you read.

- Look carefully at the figures, diagrams and other illustrations in the paper. 
- Pay special attention to graphs.
- Are the axes properly labeled? 
- Are results shown with error bars, so that conclusions are - statistically significant? 
- Common mistakes like these will separate rushed, shoddy work from the truly excellent.

- Remember to mark relevant unread references for further reading (this is a good way to learn more about the background of the paper).

.footnote[
[*] [Adapted from Keshav, Srinivasan. "How to read a paper." ACM SIGCOMM Computer Communication Review 37.3 (2007): 83-84.]()
]

---
## Three Pass Approach: The Third Pass
- To fully understand a paper, particularly if you are re-
viewer, requires a third pass. 
- This pass requires great attention to detail. 
- This pass can take about four or five hours for beginners,
and about an hour for an experienced reader. 

.footnote[
[*] [Adapted from Keshav, Srinivasan. "How to read a paper." ACM SIGCOMM Computer Communication Review 37.3 (2007): 83-84.]()
]


---
class: inverse center, middle

# Identifying Location of the Information

---
## Phage 1: To know the summary of a paper
Read the abstract first(objectives, methods, results, conclusions) 


---
## Phage 2: If interested in what this paper is all about 

Read last paragraph of introduction(research questions, research hypothesis & objectives)

---
## Phage 3: If interested in summary findings
Read first paragraph of discussion and conclusion

---
## Phage 4: If interested in strengths and limitations of the study
Read the last paragraph of discussion














---
class: center, middle

# Thanks!

Find me: <br/>
Email: [contact.jubayerhossain@gmail.com](#)<br/>
Website: https://jhossain.com/<br/> 
Github: https://github.com/hossainlab<br/>